### ISSUE TITLE
Download the image

### ISSUE THREAD

**Issue by zjph602xtc** [techbeast34/openwrt-r6080#1]
Hi, where can I download the image file? I have this router and want to flash it. 
Thank you so much! !

**Comment by techbeast34** [comment]
You can download the initial build at https://github.com/techbeast34/openwrt-r6080/releases, it has LuCI pre-installed. You'll need to flash it using the same procedure as the R6120, where you use [nmrpflash](https://github.com/jclehner/nmrpflash) to flash the initial image if you're flashing from factory.

**Comment by zjph602xtc** [comment]
Thank you! Succeed.

**Comment by techbeast34** [comment]
Hi, turns out that OpenWRT had committed support for the R6080 a day after you opened your issue. You can find the official snapshot build here: https://openwrt.org/toh/netgear/netgear_r6080
